/**
 * Bindings and secrets for the news-agent worker. `KVNamespace` comes from
 * the ambient types generated by `wrangler types --config
 * workers/news-agent/wrangler.jsonc` (workers/news-agent/worker-configuration.d.ts),
 * picked up automatically via tsconfig's `workers/**` include glob.
 */
export interface AgentEnv {
  SEEN_ARTICLES: KVNamespace;
  DEEPSEEK_API_KEY: string;
  GITHUB_TOKEN: string;
  AGENT_RUN_TOKEN: string;
}
